PythonProject/PythonProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.views.static import serve #需要导入
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),#这部分很重要
    url(r'^CollegeInfo/', include('apps.CollegeInfo.urls', namespace='CollegeInfo')),  # 学院信息模块
    url(r'^SpecialFieldInfo/', include('apps.SpecialFieldInfo.urls', namespace='SpecialFieldInfo')),  # 专业信息模块
    url(r'^ClassInfo/', include('apps.ClassInfo.urls', namespace='ClassInfo')),  # 班级信息模块
    url(r'^Student/', include('apps.Student.urls', namespace='Student')),  # 学生信息模块
    url(r'^Teacher/', include('apps.Teacher.urls', namespace='Teacher')),  # 教师信息模块
    url(r'^CourseInfo/', include('apps.CourseInfo.urls', namespace='CourseInfo')),  # 课程信息模块
    url(r'^StudentSelectCourseInfo/', include('apps.StudentSelectCourseInfo.urls', namespace='StudentSelectCourseInfo')),  # 选课信息模块
    url(r'^ScoreInfo/', include('apps.ScoreInfo.urls', namespace='ScoreInfo')),  # 成绩信息模块
    url(r'^News/', include('apps.News.urls', namespace='News')),  # 新闻信息模块

    url(r'^', include("apps.Index.urls", namespace="Index")),  # 首页模块

    url(r'^tinymce/', include('tinymce.urls')),
]

PythonProject/apps/CollegeInfo/urls.py
from apps.CollegeInfo.views import FrontAddView, FrontListView, UpdateView, DeletesView, FrontShowView, AddView, \
    ListView, OutToExcelView, BackModifyView, FrontModifyView, ListAllView
from django.conf.urls import url

# 正在部署的应用的名称
app_name = 'CollegeInfo'

urlpatterns = [
    url(r'^frontAdd$', FrontAddView.as_view(), name='frontAdd'),  # 前台添加
    url(r'^frontModify/(?P<collegeNumber>.+)$', FrontModifyView.as_view(), name='frontModify'),  # 前台更新
    url(r'^frontList$', FrontListView.as_view(), name='frontList'),  # 前台查询列表
    url(r'^frontShow/(?P<collegeNumber>.+)$', FrontShowView.as_view(), name='frontShow'),  # 前台显示详情页
    url(r'^listAll', ListAllView.as_view(), name='listAll'),  # 前台查询所有信息

    url(r'^update/(?P<collegeNumber>.+)$', UpdateView.as_view(), name='update'),  # Ajax方式更新记录

    url(r'^add$', AddView.as_view(), name='add'),  # 后台添加
    url(r'^backModify/(?P<collegeNumber>.+)$', BackModifyView.as_view(), name="backModify"),  # 后台更新
    url(r'^list$', ListView.as_view(), name='list'),  # 后台信息列表
    url(r'^deletes$', DeletesView.as_view(), name="deletes"),  # 删除记录信息
    url(r'^OutToExcel$', OutToExcelView.as_view(), name='OutToExcel')  # 导出信息到excel并下载
]

PythonProject/apps/Index/urls.py
from django.conf.urls import url
from apps.Index.views import IndexView,FrontLoginView,FrontLoginOutView,LoginView,LoginOutView,MainView,ChangePasswordView

# 正在部署的应用的名称
app_name = 'Index'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),  # 首页
    url(r'^frontLogin$', FrontLoginView.as_view(), name='frontLogin'),  # 前台登录
    url(r'^frontLoginout$', FrontLoginOutView.as_view(), name='frontLoginout'),  # 前台退出
    url(r'^login$', LoginView.as_view(), name="login"),  # 后台登录
    url(r'^loginout$', LoginOutView.as_view(), name="loginout"),  # 后台退出
    url(r'^main$', MainView.as_view(), name='main'),  # 后台主页面
    url(r'^changePassword$', ChangePasswordView.as_view(), name='changePassword')  # 管理员修改密码
]

PythonProject/apps/CollegeInfo/models.py
from django.db import models


class CollegeInfo(models.Model):
    collegeNumber = models.CharField(max_length=20, default='', primary_key=True, verbose_name='学院编号')
    collegeName = models.CharField(max_length=20, default='', verbose_name='学院名称')
    collegeBirthDate = models.CharField(max_length=20, default='', verbose_name='成立日期')
    collegeMan = models.CharField(max_length=10, default='', verbose_name='院长姓名')
    collegeTelephone = models.CharField(max_length=20, default='', verbose_name='联系电话')
    collegeMemo = models.CharField(max_length=100, default='', verbose_name='附加信息')

    class Meta:
        db_table = 't_CollegeInfo'
        verbose_name = '学院信息信息'
        verbose_name_plural = verbose_name

    def getJsonObj(self):
        collegeInfo = {
            'collegeNumber': self.collegeNumber,
            'collegeName': self.collegeName,
            'collegeBirthDate': self.collegeBirthDate,
            'collegeMan': self.collegeMan,
            'collegeTelephone': self.collegeTelephone,
            'collegeMemo': self.collegeMemo,
        }
        return collegeInfo


PythonProject/apps/CollegeInfo/views.py
from django.views.generic import View
from apps.BaseView import BaseView
from django.shortcuts import render
from django.core.paginator import Paginator
from apps.CollegeInfo.models import CollegeInfo
from django.http import JsonResponse
from django.http import FileResponse
from apps.BaseView import ImageFormatException
from django.conf import settings
import pandas as pd
import os


class FrontAddView(BaseView):  # 前台学院信息添加
    def primaryKeyExist(self, collegeNumber):  # 判断主键是否存在
        try:
            CollegeInfo.objects.get(collegeNumber=collegeNumber)
            return True
        except CollegeInfo.DoesNotExist:
            return False

    def get(self,request):

        # 使用模板
        return render(request, 'CollegeInfo/collegeInfo_frontAdd.html')

    def post(self, request):
        collegeNumber = request.POST.get('collegeInfo.collegeNumber') # 判断学院编号是否存在
        if self.primaryKeyExist(collegeNumber):
            return JsonResponse({'success': False, 'message': '学院编号已经存在'})

        collegeInfo = CollegeInfo() # 新建一个学院信息对象然后获取参数
        collegeInfo.collegeNumber = collegeNumber
        collegeInfo.collegeName = request.POST.get('collegeInfo.collegeName')
        collegeInfo.collegeBirthDate = request.POST.get('collegeInfo.collegeBirthDate')
        collegeInfo.collegeMan = request.POST.get('collegeInfo.collegeMan')
        collegeInfo.collegeTelephone = request.POST.get('collegeInfo.collegeTelephone')
        collegeInfo.collegeMemo = request.POST.get('collegeInfo.collegeMemo')
        collegeInfo.save() # 保存学院信息信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class FrontModifyView(BaseView):  # 前台修改学院信息
    def get(self, request, collegeNumber):
        context = {'collegeNumber': collegeNumber}
        return render(request, 'CollegeInfo/collegeInfo_frontModify.html', context)


class FrontListView(BaseView):  # 前台学院信息查询列表
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        self.getCurrentPage(request)  # 获取当前要显示第几页
        # 下面获取查询参数
        # 然后条件组合查询过滤
        collegeInfos = CollegeInfo.objects.all()
        # 对查询结果利用Paginator进行分页
        self.paginator = Paginator(collegeInfos, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        collegeInfos_page = self.paginator.page(self.currentPage)

        # 构造模板需要的参数
        context = {
            'collegeInfos_page': collegeInfos_page,
            'currentPage': self.currentPage,
            'totalPage': self.totalPage,
            'recordNumber': self.recordNumber,
            'startIndex': self.startIndex,
            'pageList': self.pageList,
        }
        # 渲染模板界面
        return render(request, 'CollegeInfo/collegeInfo_frontquery_result.html', context)


class FrontShowView(View):  # 前台显示学院信息详情页
    def get(self, request, collegeNumber):
        # 查询需要显示的学院信息对象
        collegeInfo = CollegeInfo.objects.get(collegeNumber=collegeNumber)
        context = {
            'collegeInfo': collegeInfo
        }
        # 渲染模板显示
        return render(request, 'CollegeInfo/collegeInfo_frontshow.html', context)


class ListAllView(View): # 前台查询所有学院信息
    def get(self,request):
        collegeInfos = CollegeInfo.objects.all()
        collegeInfoList = []
        for collegeInfo in collegeInfos:
            collegeInfoObj = {
                'collegeNumber': collegeInfo.collegeNumber,
                'collegeName': collegeInfo.collegeName,
            }
            collegeInfoList.append(collegeInfoObj)
        return JsonResponse(collegeInfoList, safe=False)


class UpdateView(BaseView):  # Ajax方式学院信息更新
    def get(self, request, collegeNumber):
        # GET方式请求查询学院信息对象并返回学院信息json格式
        collegeInfo = CollegeInfo.objects.get(collegeNumber=collegeNumber)
        return JsonResponse(collegeInfo.getJsonObj())

    def post(self, request, collegeNumber):
        # POST方式提交学院信息修改信息更新到数据库
        collegeInfo = CollegeInfo.objects.get(collegeNumber=collegeNumber)
        collegeInfo.collegeName = request.POST.get('collegeInfo.collegeName')
        collegeInfo.collegeBirthDate = request.POST.get('collegeInfo.collegeBirthDate')
        collegeInfo.collegeMan = request.POST.get('collegeInfo.collegeMan')
        collegeInfo.collegeTelephone = request.POST.get('collegeInfo.collegeTelephone')
        collegeInfo.collegeMemo = request.POST.get('collegeInfo.collegeMemo')
        collegeInfo.save()
        return JsonResponse({'success': True, 'message': '保存成功'})

class AddView(BaseView):  # 后台学院信息添加
    def primaryKeyExist(self, collegeNumber):  # 判断主键是否存在
        try:
            CollegeInfo.objects.get(collegeNumber=collegeNumber)
            return True
        except CollegeInfo.DoesNotExist:
            return False

    def get(self,request):

        # 渲染显示模板界面
        return render(request, 'CollegeInfo/collegeInfo_add.html')

    def post(self, request):
        # POST方式处理图书添加业务
        collegeNumber = request.POST.get('collegeInfo.collegeNumber') # 判断学院编号是否存在
        if self.primaryKeyExist(collegeNumber):
            return JsonResponse({'success': False, 'message': '学院编号已经存在'})

        collegeInfo = CollegeInfo() # 新建一个学院信息对象然后获取参数
        collegeInfo.collegeNumber = collegeNumber
        collegeInfo.collegeName = request.POST.get('collegeInfo.collegeName')
        collegeInfo.collegeBirthDate = request.POST.get('collegeInfo.collegeBirthDate')
        collegeInfo.collegeMan = request.POST.get('collegeInfo.collegeMan')
        collegeInfo.collegeTelephone = request.POST.get('collegeInfo.collegeTelephone')
        collegeInfo.collegeMemo = request.POST.get('collegeInfo.collegeMemo')
        collegeInfo.save() # 保存学院信息信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class BackModifyView(BaseView):  # 后台更新学院信息
    def get(self, request, collegeNumber):
        context = {'collegeNumber': collegeNumber}
        return render(request, 'CollegeInfo/collegeInfo_modify.html', context)


class ListView(BaseView):  # 后台学院信息列表
    def get(self, request):
        # 使用模板
        return render(request, 'CollegeInfo/collegeInfo_query_result.html')

    def post(self, request):
        # 获取当前要显示第几页和每页几条数据
        self.getPageAndSize(request)
        # 收集查询参数
        # 然后条件组合查询过滤
        collegeInfos = CollegeInfo.objects.all()
        # 利用Paginator对查询结果集分页
        self.paginator = Paginator(collegeInfos, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        collegeInfos_page = self.paginator.page(self.currentPage)
        # 查询的结果集转换为列表
        collegeInfoList = []
        for collegeInfo in collegeInfos_page:
            collegeInfo = collegeInfo.getJsonObj()
            collegeInfoList.append(collegeInfo)
        # 构造模板页面需要的参数
        collegeInfo_res = {
            'rows': collegeInfoList,
            'total': self.recordNumber,
        }
        # 渲染模板页面显示
        return JsonResponse(collegeInfo_res, json_dumps_params={'ensure_ascii':False})

class DeletesView(BaseView):  # 删除学院信息信息
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        collegeNumbers = self.getStrParam(request, 'collegeNumbers')
        collegeNumbers = collegeNumbers.split(',')
        count = 0
        try:
            for collegeNumber in collegeNumbers:
                CollegeInfo.objects.get(collegeNumber=collegeNumber).delete()
                count = count + 1
            message = '%s条记录删除成功！' % count
            success = True
        except Exception as e:
            message = '数据库外键约束删除失败！'
            success = False
        return JsonResponse({'success': success, 'message': message})


class OutToExcelView(BaseView):  # 导出学院信息信息到excel并下载
    def get(self, request):
        # 收集查询参数
        # 然后条件组合查询过滤
        collegeInfos = CollegeInfo.objects.all()
        #将查询结果集转换成列表
        collegeInfoList = []
        for collegeInfo in collegeInfos:
            collegeInfo = collegeInfo.getJsonObj()
            collegeInfoList.append(collegeInfo)
        # 利用pandas实现数据的导出功能
        pf = pd.DataFrame(collegeInfoList)
        # 设置要导入到excel的列
        columns_map = {
            'collegeNumber': '学院编号',
            'collegeName': '学院名称',
            'collegeBirthDate': '成立日期',
            'collegeMan': '院长姓名',
            'collegeTelephone': '联系电话',
        }
        pf = pf[columns_map.keys()]
        pf.rename(columns=columns_map, inplace=True)
        # 将空的单元格替换为空字符
        pf.fillna('', inplace=True)
        #设定文件名和导出路径
        filename = 'collegeInfos.xlsx'
        # 这个路径可以在settings中设置也可以直接手动输入
        root_path = settings.MEDIA_ROOT + '/output/'
        file_path = os.path.join(root_path, filename)
        pf.to_excel(file_path, encoding='utf-8', index=False)
        # 将生成的excel文件输出到网页下载
        file = open(file_path, 'rb')
        response = FileResponse(file)
        response['Content-Type'] = 'application/octet-stream'
        response['Content-Disposition'] = 'attachment;filename="collegeInfos.xlsx"'
        return response


PythonProject/templates/CollegeInfo/collegeInfo_frontquery_result.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
<title>学院信息查询</title>
<link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
<link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
<link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
</head>
<body style="margin-top:70px;">
<div class="container">
{% include 'header.html' %}
	<div class="row"> 
	<div style="display:none;">
		<div class="page-header">
    		<h1>学院信息查询</h1>
		</div>
		<form name="collegeInfoQueryForm" id="collegeInfoQueryForm" action="{% url 'CollegeInfo:frontList' %}" class="mar_t15" method="post">
			 {% csrf_token %}
            <input type=hidden name=currentPage value="{{ currentPage }}" />
            <button type="submit" class="btn btn-primary">查询</button>
        </form>
	</div>

		<div class="col-md-12 wow fadeInDown" data-wow-duration="0.5s">
			<div>
				<!-- Nav tabs -->
				<ul class="nav nav-tabs" role="tablist">
			    	<li><a href="{% url 'Index:index' %}">首页</a></li>
			    	<li role="presentation" class="active"><a href="#collegeInfoListPanel" aria-controls="collegeInfoListPanel" role="tab" data-toggle="tab">学院信息列表</a></li>
			    	<li role="presentation" ><a href="{% url 'CollegeInfo:frontAdd' %}" style="display:none;">添加学院信息</a></li>
				</ul>
			  	<!-- Tab panes -->
			  	<div class="tab-content">
				    <div role="tabpanel" class="tab-pane active" id="collegeInfoListPanel">
				    		<div class="row">
				    			<div class="col-md-12 top5">
				    				<div class="table-responsive">
				    				<table class="table table-condensed table-hover">
				    					<tr class="success bold"><td>序号</td><td>学院编号</td><td>学院名称</td><td>成立日期</td><td>院长姓名</td><td>联系电话</td><td>操作</td></tr>
                                        {% for collegeInfo in collegeInfos_page %}
 										<tr>
 											<td>{{ startIndex|add:forloop.counter }}</td>
 											<td>{{ collegeInfo.collegeNumber }}</td>
 											<td>{{ collegeInfo.collegeName }}</td>
 											<td>{{ collegeInfo.collegeBirthDate }}</td>
 											<td>{{ collegeInfo.collegeMan }}</td>
 											<td>{{ collegeInfo.collegeTelephone }}</td>
 											<td>
 												<a href="{% url 'CollegeInfo:frontShow' collegeInfo.collegeNumber  %}"><i class="fa fa-info"></i>&nbsp;查看</a>&nbsp;
 												<a href="#" onclick="collegeInfoEdit('{{ collegeInfo.collegeNumber }}');" style="display:none;"><i class="fa fa-pencil fa-fw"></i>编辑</a>&nbsp;
 												<a href="#" onclick="collegeInfoDelete('{{ collegeInfo.collegeNumber }}');" style="display:none;"><i class="fa fa-trash-o fa-fw"></i>删除</a>
 											</td> 
 										</tr>
 										{% endfor %}
				    				</table>
				    				</div>
				    			</div>
				    		</div>

				    		<div class="row">
					            <div class="col-md-12">
						            <nav class="pull-left">
						                <ul class="pagination">
						                    <li><a href="#" onclick="GoToPage({{ currentPage|add:-1 }},{{ totalPage }}>);" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
                                            {% for page in pageList %}
                                            {% if currentPage == page %}
						                        <li class="active"><a href="#"  onclick="GoToPage({{ page }},{{ totalPage }});">{{ page }}</a></li>
						                    {% else %}
                                                <li><a href="#"  onclick="GoToPage({{ page }},{{ totalPage }});">{{ page }}</a></li>
                                            {% endif %}
                                            {% endfor %}
						                    <li><a href="#" onclick="GoToPage({{ currentPage|add:1 }},{{ totalPage }});"><span aria-hidden="true">&raquo;</span></a></li>
						                </ul>
						            </nav>
						            <div class="pull-right" style="line-height:75px;" >共有{{ recordNumber }}条记录，当前第{{ currentPage }}/{{ totalPage }} 页</div>
					            </div>
				            </div> 
				    </div>
				</div>
			</div>
		</div>
		</div>
	</div> 
<div id="collegeInfoEditDialog" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><i class="fa fa-edit"></i>&nbsp;学院信息信息编辑</h4>
      </div>
      <div class="modal-body" style="height:450px; overflow: scroll;">
      	<form class="form-horizontal" name="collegeInfoEditForm" id="collegeInfoEditForm" enctype="multipart/form-data" method="post"  class="mar_t15">
		    {% csrf_token %}
		  <div class="form-group">
			 <label for="collegeInfo_collegeNumber_edit" class="col-md-3 text-right">学院编号:</label>
			 <div class="col-md-9"> 
			 	<input type="text" id="collegeInfo_collegeNumber_edit" name="collegeInfo.collegeNumber" class="form-control" placeholder="请输入学院编号" readOnly>
			 </div>
		  </div> 
		  <div class="form-group">
		  	 <label for="collegeInfo_collegeName_edit" class="col-md-3 text-right">学院名称:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="collegeInfo_collegeName_edit" name="collegeInfo.collegeName" class="form-control" placeholder="请输入学院名称">
			 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="collegeInfo_collegeBirthDate_edit" class="col-md-3 text-right">成立日期:</label>
		  	 <div class="col-md-9">
                <div class="input-group date collegeInfo_collegeBirthDate_edit col-md-12" data-link-field="collegeInfo_collegeBirthDate_edit"  data-link-format="yyyy-mm-dd">
                    <input class="form-control" id="collegeInfo_collegeBirthDate_edit" name="collegeInfo.collegeBirthDate" size="16" type="text" value="" placeholder="请选择成立日期" readonly>
                    <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
                    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                </div>
		  	 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="collegeInfo_collegeMan_edit" class="col-md-3 text-right">院长姓名:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="collegeInfo_collegeMan_edit" name="collegeInfo.collegeMan" class="form-control" placeholder="请输入院长姓名">
			 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="collegeInfo_collegeTelephone_edit" class="col-md-3 text-right">联系电话:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="collegeInfo_collegeTelephone_edit" name="collegeInfo.collegeTelephone" class="form-control" placeholder="请输入联系电话">
			 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="collegeInfo_collegeMemo_edit" class="col-md-3 text-right">附加信息:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="collegeInfo_collegeMemo_edit" name="collegeInfo.collegeMemo" class="form-control" placeholder="请输入附加信息">
			 </div>
		  </div>
		</form> 
	    <style>#collegeInfoEditForm .form-group {margin-bottom:5px;}  </style>
      </div>
      <div class="modal-footer"> 
      	<button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
      	<button type="button" class="btn btn-primary" onclick="ajaxCollegeInfoModify();">提交</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-datetimepicker.min.js' %}"></script>
<script src="{% static 'plugins/locales/bootstrap-datetimepicker.zh-CN.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jsdate.js' %}"></script>
<script>
/*跳转到查询结果的某页*/
function GoToPage(currentPage,totalPage) {
    if(currentPage==0) return;
    if(currentPage>totalPage) return;
    document.collegeInfoQueryForm.currentPage.value = currentPage;
    document.collegeInfoQueryForm.submit();
}

/*可以直接跳转到某页*/
function changepage(totalPage)
{
    var pageValue=document.collegeInfoQueryForm.pageValue.value;
    if(pageValue>totalPage) {
        alert('你输入的页码超出了总页数!');
        return ;
    }
    document.collegeInfoQueryForm.currentPage.value = pageValue;
    documentcollegeInfoQueryForm.submit();
}

/*弹出修改学院信息界面并初始化数据*/
function collegeInfoEdit(collegeNumber) {
	$.ajax({
		url :  '/CollegeInfo/update/' + collegeNumber,
		type : "get",
		dataType: "json",
		success : function (collegeInfo, response, status) {
			if (collegeInfo) {
				$("#collegeInfo_collegeNumber_edit").val(collegeInfo.collegeNumber);
				$("#collegeInfo_collegeName_edit").val(collegeInfo.collegeName);
				$("#collegeInfo_collegeBirthDate_edit").val(collegeInfo.collegeBirthDate);
				$("#collegeInfo_collegeMan_edit").val(collegeInfo.collegeMan);
				$("#collegeInfo_collegeTelephone_edit").val(collegeInfo.collegeTelephone);
				$("#collegeInfo_collegeMemo_edit").val(collegeInfo.collegeMemo);
				$('#collegeInfoEditDialog').modal('show');
			} else {
				alert("获取信息失败！");
			}
		}
	});
}

/*删除学院信息信息*/
function collegeInfoDelete(collegeNumber) {
    var csrf = $('input[name="csrfmiddlewaretoken"]').val();
	if(confirm("确认删除这个记录")) {
		$.ajax({
			type : "POST",
			url : "/CollegeInfo/deletes",
			data : {
				collegeNumbers : collegeNumber,
                "csrfmiddlewaretoken": csrf
			},
			success : function (obj) {
				if (obj.success) {
					alert("删除成功");
					$("#collegeInfoQueryForm").submit();
					//location.href= basePath + "CollegeInfo/frontlist";
				}
				else 
					alert(obj.message);
			},
		});
	}
}

/*ajax方式提交学院信息信息表单给服务器端修改*/
function ajaxCollegeInfoModify() {
	$.ajax({
		url :   '/CollegeInfo/update/' + $("#collegeInfo_collegeNumber_edit").val(),
		type : "post",
		dataType: "json",
		data: new FormData($("#collegeInfoEditForm")[0]),
		success : function (obj, response, status) {
            if(obj.success){
                alert("信息修改成功！");
                location.href= basePath + "CollegeInfo/frontlist";
            }else{
                alert(obj.message);
            } 
		},
		processData: false,
		contentType: false,
	});
}

$(function(){
	/*小屏幕导航点击关闭菜单*/
    $('.navbar-collapse a').click(function(){
        $('.navbar-collapse').collapse('hide');
    });
    new WOW().init();

    /*成立日期组件*/
    $('.collegeInfo_collegeBirthDate_edit').datetimepicker({
    	language:  'zh-CN',  //语言
    	format: 'yyyy-mm-dd',
    	minView: 2,
    	weekStart: 1,
    	todayBtn:  1,
    	autoclose: 1,
    	minuteStep: 1,
    	todayHighlight: 1,
    	startView: 2,
    	forceParse: 0
    });
})
</script>
</body>
</html>
