PythonProject/PythonProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.views.static import serve #需要导入
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),#这部分很重要
    url(r'^CollegeInfo/', include('apps.CollegeInfo.urls', namespace='CollegeInfo')),  # 学院信息模块
    url(r'^SpecialFieldInfo/', include('apps.SpecialFieldInfo.urls', namespace='SpecialFieldInfo')),  # 专业信息模块
    url(r'^ClassInfo/', include('apps.ClassInfo.urls', namespace='ClassInfo')),  # 班级信息模块
    url(r'^Student/', include('apps.Student.urls', namespace='Student')),  # 学生信息模块
    url(r'^Teacher/', include('apps.Teacher.urls', namespace='Teacher')),  # 教师信息模块
    url(r'^CourseInfo/', include('apps.CourseInfo.urls', namespace='CourseInfo')),  # 课程信息模块
    url(r'^StudentSelectCourseInfo/', include('apps.StudentSelectCourseInfo.urls', namespace='StudentSelectCourseInfo')),  # 选课信息模块
    url(r'^ScoreInfo/', include('apps.ScoreInfo.urls', namespace='ScoreInfo')),  # 成绩信息模块
    url(r'^News/', include('apps.News.urls', namespace='News')),  # 新闻信息模块

    url(r'^', include("apps.Index.urls", namespace="Index")),  # 首页模块

    url(r'^tinymce/', include('tinymce.urls')),
]

PythonProject/apps/CourseInfo/urls.py
from apps.CourseInfo.views import FrontAddView, FrontListView, UpdateView, DeletesView, FrontShowView, AddView, \
    ListView, OutToExcelView, BackModifyView, FrontModifyView, ListAllView
from django.conf.urls import url

# 正在部署的应用的名称
app_name = 'CourseInfo'

urlpatterns = [
    url(r'^frontAdd$', FrontAddView.as_view(), name='frontAdd'),  # 前台添加
    url(r'^frontModify/(?P<courseNumber>.+)$', FrontModifyView.as_view(), name='frontModify'),  # 前台更新
    url(r'^frontList$', FrontListView.as_view(), name='frontList'),  # 前台查询列表
    url(r'^frontShow/(?P<courseNumber>.+)$', FrontShowView.as_view(), name='frontShow'),  # 前台显示详情页
    url(r'^listAll', ListAllView.as_view(), name='listAll'),  # 前台查询所有信息

    url(r'^update/(?P<courseNumber>.+)$', UpdateView.as_view(), name='update'),  # Ajax方式更新记录

    url(r'^add$', AddView.as_view(), name='add'),  # 后台添加
    url(r'^backModify/(?P<courseNumber>.+)$', BackModifyView.as_view(), name="backModify"),  # 后台更新
    url(r'^list$', ListView.as_view(), name='list'),  # 后台信息列表
    url(r'^deletes$', DeletesView.as_view(), name="deletes"),  # 删除记录信息
    url(r'^OutToExcel$', OutToExcelView.as_view(), name='OutToExcel')  # 导出信息到excel并下载
]

PythonProject/apps/Index/urls.py
from django.conf.urls import url
from apps.Index.views import IndexView,FrontLoginView,FrontLoginOutView,LoginView,LoginOutView,MainView,ChangePasswordView

# 正在部署的应用的名称
app_name = 'Index'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),  # 首页
    url(r'^frontLogin$', FrontLoginView.as_view(), name='frontLogin'),  # 前台登录
    url(r'^frontLoginout$', FrontLoginOutView.as_view(), name='frontLoginout'),  # 前台退出
    url(r'^login$', LoginView.as_view(), name="login"),  # 后台登录
    url(r'^loginout$', LoginOutView.as_view(), name="loginout"),  # 后台退出
    url(r'^main$', MainView.as_view(), name='main'),  # 后台主页面
    url(r'^changePassword$', ChangePasswordView.as_view(), name='changePassword')  # 管理员修改密码
]

PythonProject/apps/CourseInfo/models.py
from django.db import models
from apps.Teacher.models import Teacher


class CourseInfo(models.Model):
    courseNumber = models.CharField(max_length=20, default='', primary_key=True, verbose_name='课程编号')
    courseName = models.CharField(max_length=20, default='', verbose_name='课程名称')
    coursePhoto = models.ImageField(upload_to='img', max_length='100', verbose_name='课程图片')
    courseTeacher = models.ForeignKey(Teacher,  db_column='courseTeacher', on_delete=models.PROTECT, verbose_name='上课老师')
    courseTime = models.CharField(max_length=40, default='', verbose_name='上课时间')
    coursePlace = models.CharField(max_length=40, default='', verbose_name='上课地点')
    courseScore = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='课程学分')
    courseMemo = models.CharField(max_length=100, default='', verbose_name='附加信息')

    class Meta:
        db_table = 't_CourseInfo'
        verbose_name = '课程信息信息'
        verbose_name_plural = verbose_name

    def getJsonObj(self):
        courseInfo = {
            'courseNumber': self.courseNumber,
            'courseName': self.courseName,
            'coursePhoto': self.coursePhoto.url,
            'courseTeacher': self.courseTeacher.teacherName,
            'courseTeacherPri': self.courseTeacher.teacherNumber,
            'courseTime': self.courseTime,
            'coursePlace': self.coursePlace,
            'courseScore': self.courseScore,
            'courseMemo': self.courseMemo,
        }
        return courseInfo


PythonProject/templates/CourseInfo/courseInfo_frontquery_result.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
<title>课程信息查询</title>
<link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
<link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
<link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
</head>
<body style="margin-top:70px;">
<div class="container">
{% include 'header.html' %}
	<div class="col-md-3 wow fadeInLeft">
		<div class="page-header">
    		<h1>课程信息查询</h1>
		</div>
		<form name="courseInfoQueryForm" id="courseInfoQueryForm" action="{% url 'CourseInfo:frontList' %}" class="mar_t15" method="post">
			 {% csrf_token %}
			<div class="form-group">
				<label for="courseNumber">课程编号:</label>
				<input type="text" id="courseNumber" name="courseNumber" value="{{ courseNumber }}" class="form-control" placeholder="请输入课程编号">
			</div>
			<div class="form-group">
				<label for="courseName">课程名称:</label>
				<input type="text" id="courseName" name="courseName" value="{{ courseName }}" class="form-control" placeholder="请输入课程名称">
			</div>
            <div class="form-group">
            	<label for="courseTeacher_teacherNumber">上课老师：</label>
                <select id="courseTeacher_teacherNumber" name="courseTeacher.teacherNumber" class="form-control">
                	<option value="">不限制</option>
                    {% for teacher in teachers %}
                        {% if teacher.teacherNumber == courseTeacher_teacherNumber %}
                             <option value="{{teacher.teacherNumber }}" selected>{{ teacher.teacherName }}</option>
                        {% else %}
                            <option value="{{ teacher.teacherNumber }}">{{ teacher.teacherName }}</option>
                        {% endif %}
	 				{% endfor %}
 			</select>
            </div>
            <input type=hidden name=currentPage value="{{ currentPage }}" />
            <button type="submit" class="btn btn-primary">查询</button>
        </form>
	</div>

	<div class="col-md-9 wow fadeInRight">
		<ul class="breadcrumb">
  			<li><a href="{% url 'Index:index' %}">首页</a></li>
  			<li><a href="{% url 'CourseInfo:frontList' %}">课程信息信息列表</a></li>
  			<li class="active">查询结果显示</li>
  			<a class="pull-right" href="{% url 'CourseInfo:frontAdd' %}" style="display:none;">添加课程信息</a>
		</ul>
		<div class="row">
            {% for courseInfo in courseInfos_page %}
                {% if forloop.counter|add:-1|divisibleby:4 %}
			<div class="col-md-3 bottom15" style="clear: left;">
                {% else %}
            <div class="col-md-3 bottom15">
                {% endif %}
			  <a  href="{% url 'CourseInfo:frontShow' courseInfo.courseNumber %}"><img class="img-responsive" src="{{ courseInfo.coursePhoto.url }}" /></a>
			     <div class="showFields">
			     	<div class="field">
	            		课程编号:{{ courseInfo.courseNumber }}
			     	</div>
			     	<div class="field">
	            		课程名称:{{ courseInfo.courseName }}
			     	</div>
			     	<div class="field">
	            		上课老师:{{ courseInfo.courseTeacher.teacherName }}
			     	</div>
			     	<div class="field">
	            		上课时间:{{ courseInfo.courseTime }}
			     	</div>
			     	<div class="field">
	            		上课地点:{{ courseInfo.coursePlace }}
			     	</div>
			     	<div class="field">
	            		课程学分:{{ courseInfo.courseScore }}
			     	</div>
			        <a class="btn btn-primary top5" href="{% url 'CourseInfo:frontShow' courseInfo.courseNumber  %}">详情</a>
			        <a class="btn btn-primary top5" onclick="courseInfoEdit('{{ courseInfo.courseNumber }}');" style="display: none;">修改</a>
			        <a class="btn btn-primary top5" onclick="courseInfoDelete('{{ courseInfo.courseNumber }}');" style="display: none;">删除</a>
			     </div>
			</div>
			{% endfor %}

			<div class="row">
				<div class="col-md-12">
					<nav class="pull-left">
						<ul class="pagination">
							<li><a href="#" onclick="GoToPage({{ currentPage|add:-1 }},{{ totalPage }});" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
							{% for page in pageList %}
                                            {% if currentPage == page %}
						                        <li class="active"><a href="#"  onclick="GoToPage({{ page }},{{ totalPage }});">{{ page }}</a></li>
						                    {% else %}
                                                <li><a href="#"  onclick="GoToPage({{ page }},{{ totalPage }});">{{ page }}</a></li>
                                            {% endif %}
                                            {% endfor %}
						                    <li><a href="#" onclick="GoToPage({{ currentPage|add:1 }},{{ totalPage }});"><span aria-hidden="true">&raquo;</span></a></li>
						</ul>
					</nav>
					<div class="pull-right" style="line-height:75px;" >共有{{ recordNumber }}条记录，当前第{{ currentPage }}/{{ totalPage }} 页</div>
				</div>
			</div>
		</div>
	</div>

  </div>
</div>
<div id="courseInfoEditDialog" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><i class="fa fa-edit"></i>&nbsp;课程信息信息编辑</h4>
      </div>
      <div class="modal-body" style="height:450px; overflow: scroll;">
      	<form class="form-horizontal" name="courseInfoEditForm" id="courseInfoEditForm" enctype="multipart/form-data" method="post"  class="mar_t15">
		    {% csrf_token %}
		  <div class="form-group">
			 <label for="courseInfo_courseNumber_edit" class="col-md-3 text-right">课程编号:</label>
			 <div class="col-md-9"> 
			 	<input type="text" id="courseInfo_courseNumber_edit" name="courseInfo.courseNumber" class="form-control" placeholder="请输入课程编号" readOnly>
			 </div>
		  </div> 
		  <div class="form-group">
		  	 <label for="courseInfo_courseName_edit" class="col-md-3 text-right">课程名称:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="courseInfo_courseName_edit" name="courseInfo.courseName" class="form-control" placeholder="请输入课程名称">
			 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="courseInfo_coursePhoto_edit" class="col-md-3 text-right">课程图片:</label>
		  	 <div class="col-md-9">
			    <img  class="img-responsive" id="courseInfo_coursePhotoImg" border="0px"/><br/>
			    <input id="courseInfo_coursePhoto" name="courseInfo.coursePhoto" type="file" size="50" />
		  	 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="courseInfo_courseTeacher_teacherNumber_edit" class="col-md-3 text-right">上课老师:</label>
		  	 <div class="col-md-9">
			    <select id="courseInfo_courseTeacher_teacherNumber_edit" name="courseInfo.courseTeacher.teacherNumber" class="form-control">
                    {% for teacher in teachers %}
                        <option value="{{ teacher.teacherNumber }}">{{ teacher.teacherName }}</option>
                    {% endfor %}
			    </select>
		  	 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="courseInfo_courseTime_edit" class="col-md-3 text-right">上课时间:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="courseInfo_courseTime_edit" name="courseInfo.courseTime" class="form-control" placeholder="请输入上课时间">
			 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="courseInfo_coursePlace_edit" class="col-md-3 text-right">上课地点:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="courseInfo_coursePlace_edit" name="courseInfo.coursePlace" class="form-control" placeholder="请输入上课地点">
			 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="courseInfo_courseScore_edit" class="col-md-3 text-right">课程学分:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="courseInfo_courseScore_edit" name="courseInfo.courseScore" class="form-control" placeholder="请输入课程学分">
			 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="courseInfo_courseMemo_edit" class="col-md-3 text-right">附加信息:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="courseInfo_courseMemo_edit" name="courseInfo.courseMemo" class="form-control" placeholder="请输入附加信息">
			 </div>
		  </div>
		</form> 
	    <style>#courseInfoEditForm .form-group {margin-bottom:5px;}  </style>
      </div>
      <div class="modal-footer"> 
      	<button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
      	<button type="button" class="btn btn-primary" onclick="ajaxCourseInfoModify();">提交</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-datetimepicker.min.js' %}"></script>
<script src="{% static 'plugins/locales/bootstrap-datetimepicker.zh-CN.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jsdate.js' %}"></script>
<script>
/*跳转到查询结果的某页*/
function GoToPage(currentPage,totalPage) {
    if(currentPage==0) return;
    if(currentPage>totalPage) return;
    document.courseInfoQueryForm.currentPage.value = currentPage;
    document.courseInfoQueryForm.submit();
}

/*可以直接跳转到某页*/
function changepage(totalPage)
{
    var pageValue=document.courseInfoQueryForm.pageValue.value;
    if(pageValue>totalPage) {
        alert('你输入的页码超出了总页数!');
        return ;
    }
    document.courseInfoQueryForm.currentPage.value = pageValue;
    documentcourseInfoQueryForm.submit();
}

/*弹出修改课程信息界面并初始化数据*/
function courseInfoEdit(courseNumber) {
	$.ajax({
		url :  '/CourseInfo/update/' + courseNumber,
		type : "get",
		dataType: "json",
		success : function (courseInfo, response, status) {
			if (courseInfo) {
				$("#courseInfo_courseNumber_edit").val(courseInfo.courseNumber);
				$("#courseInfo_courseName_edit").val(courseInfo.courseName);
				$("#courseInfo_coursePhotoImg").attr("src", courseInfo.coursePhoto);
				$.ajax({
					url: "{% url 'Teacher:listAll' %}",
					type: "get",
					success: function(teachers,response,status) { 
						$("#courseInfo_courseTeacher_teacherNumber_edit").empty();
						var html="";
		        		$(teachers).each(function(i,teacher){
		        			html += "<option value='" + teacher.teacherNumber + "'>" + teacher.teacherName + "</option>";
		        		});
		        		$("#courseInfo_courseTeacher_teacherNumber_edit").html(html);
		        		$("#courseInfo_courseTeacher_teacherNumber_edit").val(courseInfo.courseTeacherPri);
					}
				});
				$("#courseInfo_courseTime_edit").val(courseInfo.courseTime);
				$("#courseInfo_coursePlace_edit").val(courseInfo.coursePlace);
				$("#courseInfo_courseScore_edit").val(courseInfo.courseScore);
				$("#courseInfo_courseMemo_edit").val(courseInfo.courseMemo);
				$('#courseInfoEditDialog').modal('show');
			} else {
				alert("获取信息失败！");
			}
		}
	});
}

/*删除课程信息信息*/
function courseInfoDelete(courseNumber) {
    var csrf = $('input[name="csrfmiddlewaretoken"]').val();
	if(confirm("确认删除这个记录")) {
		$.ajax({
			type : "POST",
			url : "/CourseInfo/deletes",
			data : {
				courseNumbers : courseNumber,
                "csrfmiddlewaretoken": csrf
			},
			success : function (obj) {
				if (obj.success) {
					alert("删除成功");
					$("#courseInfoQueryForm").submit();
					//location.href= basePath + "CourseInfo/frontlist";
				}
				else 
					alert(obj.message);
			},
		});
	}
}

/*ajax方式提交课程信息信息表单给服务器端修改*/
function ajaxCourseInfoModify() {
	$.ajax({
		url :   '/CourseInfo/update/' + $("#courseInfo_courseNumber_edit").val(),
		type : "post",
		dataType: "json",
		data: new FormData($("#courseInfoEditForm")[0]),
		success : function (obj, response, status) {
            if(obj.success){
                alert("信息修改成功！");
                $("#courseInfoQueryForm").submit();
            }else{
                alert(obj.message);
            } 
		},
		processData: false,
		contentType: false,
	});
}

$(function(){
	/*小屏幕导航点击关闭菜单*/
    $('.navbar-collapse a').click(function(){
        $('.navbar-collapse').collapse('hide');
    });
    new WOW().init();

})
</script>
</body>
</html>


PythonProject/templates/CourseInfo/courseInfo_query_result.html
{% include 'check_logstate.html' %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static '/css/courseInfo.css' %}" />

{% csrf_token %}
<div id="courseInfo_manage"></div>
<div id="courseInfo_manage_tool" style="padding:5px;">
	<div style="margin-bottom:5px;">
		<a href="#" class="easyui-linkbutton" iconCls="icon-edit-new" plain="true" onclick="courseInfo_manage_tool.edit();">修改</a>
		<a href="#" class="easyui-linkbutton" iconCls="icon-delete-new" plain="true" onclick="courseInfo_manage_tool.remove();">删除</a>
		<a href="#" class="easyui-linkbutton" iconCls="icon-reload" plain="true"  onclick="courseInfo_manage_tool.reload();">刷新</a>
		<a href="#" class="easyui-linkbutton" iconCls="icon-redo" plain="true" onclick="courseInfo_manage_tool.redo();">取消选择</a>
		<a href="#" class="easyui-linkbutton" iconCls="icon-export" plain="true" onclick="courseInfo_manage_tool.exportExcel();">导出到excel</a>
	</div>
	<div style="padding:0 0 0 7px;color:#333;">
		<form id="courseInfoQueryForm" method="get">
			课程编号：<input type="text" class="textbox" id="courseNumber" name="courseNumber" style="width:110px" />
			课程名称：<input type="text" class="textbox" id="courseName" name="courseName" style="width:110px" />
			上课老师：<input class="textbox" type="text" id="courseTeacher_teacherNumber_query" name="courseTeacher.teacherNumber" style="width: auto"/>
			<a href="#" class="easyui-linkbutton" iconCls="icon-search" onclick="courseInfo_manage_tool.search();">查询</a>
		</form>	
	</div>
</div>

<div id="courseInfoEditDiv">
	<form id="courseInfoEditForm" enctype="multipart/form-data"  method="post">
        {% csrf_token %}
		<div>
			<span class="label">课程编号:</span>
			<span class="inputControl">
				<input class="textbox" type="text" id="courseInfo_courseNumber_edit" name="courseInfo.courseNumber" style="width:200px" />
			</span>
		</div>
		<div>
			<span class="label">课程名称:</span>
			<span class="inputControl">
				<input class="textbox" type="text" id="courseInfo_courseName_edit" name="courseInfo.courseName" style="width:200px" />

			</span>

		</div>
		<div>
			<span class="label">课程图片:</span>
			<span class="inputControl">
				<img id="courseInfo_coursePhotoImg" width="200px" border="0px"/><br/>
				<input id="courseInfo_coursePhoto" name="courseInfo.coursePhoto" type="file" size="50" />
			</span>
		</div>
		<div>
			<span class="label">上课老师:</span>
			<span class="inputControl">
				<input class="textbox"  id="courseInfo_courseTeacher_teacherNumber_edit" name="courseInfo.courseTeacher.teacherNumber" style="width: auto"/>
			</span>
		</div>
		<div>
			<span class="label">上课时间:</span>
			<span class="inputControl">
				<input class="textbox" type="text" id="courseInfo_courseTime_edit" name="courseInfo.courseTime" style="width:200px" />

			</span>

		</div>
		<div>
			<span class="label">上课地点:</span>
			<span class="inputControl">
				<input class="textbox" type="text" id="courseInfo_coursePlace_edit" name="courseInfo.coursePlace" style="width:200px" />

			</span>

		</div>
		<div>
			<span class="label">课程学分:</span>
			<span class="inputControl">
				<input class="textbox" type="text" id="courseInfo_courseScore_edit" name="courseInfo.courseScore" style="width:80px" />

			</span>

		</div>
		<div>
			<span class="label">附加信息:</span>
			<span class="inputControl">
				<input class="textbox" type="text" id="courseInfo_courseMemo_edit" name="courseInfo.courseMemo" style="width:200px" />

			</span>

		</div>
	</form>
</div>
<script type="text/javascript" src="{% static 'js/CourseInfo/courseInfo_manage.js' %}"></script>