PythonProject/PythonProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.views.static import serve #需要导入
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),#这部分很重要
    url(r'^CollegeInfo/', include('apps.CollegeInfo.urls', namespace='CollegeInfo')),  # 学院信息模块
    url(r'^SpecialFieldInfo/', include('apps.SpecialFieldInfo.urls', namespace='SpecialFieldInfo')),  # 专业信息模块
    url(r'^ClassInfo/', include('apps.ClassInfo.urls', namespace='ClassInfo')),  # 班级信息模块
    url(r'^Student/', include('apps.Student.urls', namespace='Student')),  # 学生信息模块
    url(r'^Teacher/', include('apps.Teacher.urls', namespace='Teacher')),  # 教师信息模块
    url(r'^CourseInfo/', include('apps.CourseInfo.urls', namespace='CourseInfo')),  # 课程信息模块
    url(r'^StudentSelectCourseInfo/', include('apps.StudentSelectCourseInfo.urls', namespace='StudentSelectCourseInfo')),  # 选课信息模块
    url(r'^ScoreInfo/', include('apps.ScoreInfo.urls', namespace='ScoreInfo')),  # 成绩信息模块
    url(r'^News/', include('apps.News.urls', namespace='News')),  # 新闻信息模块

    url(r'^', include("apps.Index.urls", namespace="Index")),  # 首页模块

    url(r'^tinymce/', include('tinymce.urls')),
]

PythonProject/apps/Index/urls.py
from django.conf.urls import url
from apps.Index.views import IndexView,FrontLoginView,FrontLoginOutView,LoginView,LoginOutView,MainView,ChangePasswordView

# 正在部署的应用的名称
app_name = 'Index'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),  # 首页
    url(r'^frontLogin$', FrontLoginView.as_view(), name='frontLogin'),  # 前台登录
    url(r'^frontLoginout$', FrontLoginOutView.as_view(), name='frontLoginout'),  # 前台退出
    url(r'^login$', LoginView.as_view(), name="login"),  # 后台登录
    url(r'^loginout$', LoginOutView.as_view(), name="loginout"),  # 后台退出
    url(r'^main$', MainView.as_view(), name='main'),  # 后台主页面
    url(r'^changePassword$', ChangePasswordView.as_view(), name='changePassword')  # 管理员修改密码
]

PythonProject/apps/News/urls.py
from apps.News.views import FrontAddView, FrontListView, UpdateView, DeletesView, FrontShowView, AddView, \
    ListView, OutToExcelView, BackModifyView, FrontModifyView, ListAllView
from django.conf.urls import url

# 正在部署的应用的名称
app_name = 'News'

urlpatterns = [
    url(r'^frontAdd$', FrontAddView.as_view(), name='frontAdd'),  # 前台添加
    url(r'^frontModify/(?P<newsId>.+)$', FrontModifyView.as_view(), name='frontModify'),  # 前台更新
    url(r'^frontList$', FrontListView.as_view(), name='frontList'),  # 前台查询列表
    url(r'^frontShow/(?P<newsId>.+)$', FrontShowView.as_view(), name='frontShow'),  # 前台显示详情页
    url(r'^listAll', ListAllView.as_view(), name='listAll'),  # 前台查询所有信息

    url(r'^update/(?P<newsId>.+)$', UpdateView.as_view(), name='update'),  # Ajax方式更新记录

    url(r'^add$', AddView.as_view(), name='add'),  # 后台添加
    url(r'^backModify/(?P<newsId>.+)$', BackModifyView.as_view(), name="backModify"),  # 后台更新
    url(r'^list$', ListView.as_view(), name='list'),  # 后台信息列表
    url(r'^deletes$', DeletesView.as_view(), name="deletes"),  # 删除记录信息
    url(r'^OutToExcel$', OutToExcelView.as_view(), name='OutToExcel')  # 导出信息到excel并下载
]

PythonProject/apps/News/models.py
from django.db import models


class News(models.Model):
    newsId = models.AutoField(primary_key=True, verbose_name='记录编号')
    newsTitle = models.CharField(max_length=50, default='', verbose_name='新闻标题')
    newsContent = models.CharField(max_length=500, default='', verbose_name='新闻内容')
    newsDate = models.CharField(max_length=20, default='', verbose_name='发布日期')
    newsPhoto = models.ImageField(upload_to='img', max_length='100', verbose_name='新闻图片')

    class Meta:
        db_table = 't_News'
        verbose_name = '新闻信息信息'
        verbose_name_plural = verbose_name

    def getJsonObj(self):
        news = {
            'newsId': self.newsId,
            'newsTitle': self.newsTitle,
            'newsContent': self.newsContent,
            'newsDate': self.newsDate,
            'newsPhoto': self.newsPhoto.url,
        }
        return news


PythonProject/apps/News/views.py
from django.views.generic import View
from apps.BaseView import BaseView
from django.shortcuts import render
from django.core.paginator import Paginator
from apps.News.models import News
from django.http import JsonResponse
from django.http import FileResponse
from apps.BaseView import ImageFormatException
from django.conf import settings
import pandas as pd
import os


class FrontAddView(BaseView):  # 前台新闻信息添加
    def get(self,request):

        # 使用模板
        return render(request, 'News/news_frontAdd.html')

    def post(self, request):
        news = News() # 新建一个新闻信息对象然后获取参数
        news.newsTitle = request.POST.get('news.newsTitle')
        news.newsContent = request.POST.get('news.newsContent')
        news.newsDate = request.POST.get('news.newsDate')
        try:
            news.newsPhoto = self.uploadImageFile(request,'news.newsPhoto')
        except ImageFormatException as ife:
            return JsonResponse({'success': False, 'message': ife.error})
        news.save() # 保存新闻信息信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class FrontModifyView(BaseView):  # 前台修改新闻信息
    def get(self, request, newsId):
        context = {'newsId': newsId}
        return render(request, 'News/news_frontModify.html', context)


class FrontListView(BaseView):  # 前台新闻信息查询列表
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        self.getCurrentPage(request)  # 获取当前要显示第几页
        # 下面获取查询参数
        newsTitle = self.getStrParam(request, 'newsTitle')
        newsDate = self.getStrParam(request, 'newsDate')
        # 然后条件组合查询过滤
        newss = News.objects.all()
        if newsTitle != '':
            newss = newss.filter(newsTitle__contains=newsTitle)
        if newsDate != '':
            newss = newss.filter(newsDate__contains=newsDate)
        # 对查询结果利用Paginator进行分页
        self.paginator = Paginator(newss, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        newss_page = self.paginator.page(self.currentPage)

        # 构造模板需要的参数
        context = {
            'newss_page': newss_page,
            'newsTitle': newsTitle,
            'newsDate': newsDate,
            'currentPage': self.currentPage,
            'totalPage': self.totalPage,
            'recordNumber': self.recordNumber,
            'startIndex': self.startIndex,
            'pageList': self.pageList,
        }
        # 渲染模板界面
        return render(request, 'News/news_frontquery_result.html', context)


class FrontShowView(View):  # 前台显示新闻信息详情页
    def get(self, request, newsId):
        # 查询需要显示的新闻信息对象
        news = News.objects.get(newsId=newsId)
        context = {
            'news': news
        }
        # 渲染模板显示
        return render(request, 'News/news_frontshow.html', context)


class ListAllView(View): # 前台查询所有新闻信息
    def get(self,request):
        newss = News.objects.all()
        newsList = []
        for news in newss:
            newsObj = {
                'newsId': news.newsId,
                'newsTitle': news.newsTitle,
            }
            newsList.append(newsObj)
        return JsonResponse(newsList, safe=False)


class UpdateView(BaseView):  # Ajax方式新闻信息更新
    def get(self, request, newsId):
        # GET方式请求查询新闻信息对象并返回新闻信息json格式
        news = News.objects.get(newsId=newsId)
        return JsonResponse(news.getJsonObj())

    def post(self, request, newsId):
        # POST方式提交新闻信息修改信息更新到数据库
        news = News.objects.get(newsId=newsId)
        news.newsTitle = request.POST.get('news.newsTitle')
        news.newsContent = request.POST.get('news.newsContent')
        news.newsDate = request.POST.get('news.newsDate')
        try:
            newsPhotoName = self.uploadImageFile(request, 'news.newsPhoto')
        except ImageFormatException as ife:
            return JsonResponse({'success': False, 'message': ife.error})
        if newsPhotoName != 'img/NoImage.jpg':
            news.newsPhoto = newsPhotoName
        news.save()
        return JsonResponse({'success': True, 'message': '保存成功'})

class AddView(BaseView):  # 后台新闻信息添加
    def get(self,request):

        # 渲染显示模板界面
        return render(request, 'News/news_add.html')

    def post(self, request):
        # POST方式处理图书添加业务
        news = News() # 新建一个新闻信息对象然后获取参数
        news.newsTitle = request.POST.get('news.newsTitle')
        news.newsContent = request.POST.get('news.newsContent')
        news.newsDate = request.POST.get('news.newsDate')
        try:
            news.newsPhoto = self.uploadImageFile(request,'news.newsPhoto')
        except ImageFormatException as ife:
            return JsonResponse({'success': False, 'message': ife.error})
        news.save() # 保存新闻信息信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class BackModifyView(BaseView):  # 后台更新新闻信息
    def get(self, request, newsId):
        context = {'newsId': newsId}
        return render(request, 'News/news_modify.html', context)


class ListView(BaseView):  # 后台新闻信息列表
    def get(self, request):
        # 使用模板
        return render(request, 'News/news_query_result.html')

    def post(self, request):
        # 获取当前要显示第几页和每页几条数据
        self.getPageAndSize(request)
        # 收集查询参数
        newsTitle = self.getStrParam(request, 'newsTitle')
        newsDate = self.getStrParam(request, 'newsDate')
        # 然后条件组合查询过滤
        newss = News.objects.all()
        if newsTitle != '':
            newss = newss.filter(newsTitle__contains=newsTitle)
        if newsDate != '':
            newss = newss.filter(newsDate__contains=newsDate)
        # 利用Paginator对查询结果集分页
        self.paginator = Paginator(newss, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        newss_page = self.paginator.page(self.currentPage)
        # 查询的结果集转换为列表
        newsList = []
        for news in newss_page:
            news = news.getJsonObj()
            newsList.append(news)
        # 构造模板页面需要的参数
        news_res = {
            'rows': newsList,
            'total': self.recordNumber,
        }
        # 渲染模板页面显示
        return JsonResponse(news_res, json_dumps_params={'ensure_ascii':False})

class DeletesView(BaseView):  # 删除新闻信息信息
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        newsIds = self.getStrParam(request, 'newsIds')
        newsIds = newsIds.split(',')
        count = 0
        try:
            for newsId in newsIds:
                News.objects.get(newsId=newsId).delete()
                count = count + 1
            message = '%s条记录删除成功！' % count
            success = True
        except Exception as e:
            message = '数据库外键约束删除失败！'
            success = False
        return JsonResponse({'success': success, 'message': message})


class OutToExcelView(BaseView):  # 导出新闻信息信息到excel并下载
    def get(self, request):
        # 收集查询参数
        newsTitle = self.getStrParam(request, 'newsTitle')
        newsDate = self.getStrParam(request, 'newsDate')
        # 然后条件组合查询过滤
        newss = News.objects.all()
        if newsTitle != '':
            newss = newss.filter(newsTitle__contains=newsTitle)
        if newsDate != '':
            newss = newss.filter(newsDate__contains=newsDate)
        #将查询结果集转换成列表
        newsList = []
        for news in newss:
            news = news.getJsonObj()
            newsList.append(news)
        # 利用pandas实现数据的导出功能
        pf = pd.DataFrame(newsList)
        # 设置要导入到excel的列
        columns_map = {
            'newsId': '记录编号',
            'newsTitle': '新闻标题',
            'newsContent': '新闻内容',
            'newsDate': '发布日期',
        }
        pf = pf[columns_map.keys()]
        pf.rename(columns=columns_map, inplace=True)
        # 将空的单元格替换为空字符
        pf.fillna('', inplace=True)
        #设定文件名和导出路径
        filename = 'newss.xlsx'
        # 这个路径可以在settings中设置也可以直接手动输入
        root_path = settings.MEDIA_ROOT + '/output/'
        file_path = os.path.join(root_path, filename)
        pf.to_excel(file_path, encoding='utf-8', index=False)
        # 将生成的excel文件输出到网页下载
        file = open(file_path, 'rb')
        response = FileResponse(file)
        response['Content-Type'] = 'application/octet-stream'
        response['Content-Disposition'] = 'attachment;filename="newss.xlsx"'
        return response


PythonProject/templates/News/news_frontquery_result.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
<title>新闻信息查询</title>
<link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
<link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
<link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
</head>
<body style="margin-top:70px;">
<div class="container">
{% include 'header.html' %}
	<div class="col-md-3 wow fadeInLeft">
		<div class="page-header">
    		<h1>新闻信息查询</h1>
		</div>
		<form name="newsQueryForm" id="newsQueryForm" action="{% url 'News:frontList' %}" class="mar_t15" method="post">
			 {% csrf_token %}
			<div class="form-group">
				<label for="newsTitle">新闻标题:</label>
				<input type="text" id="newsTitle" name="newsTitle" value="{{ newsTitle }}" class="form-control" placeholder="请输入新闻标题">
			</div>
			<div class="form-group">
				<label for="newsDate">发布日期:</label>
				<input type="text" id="newsDate" name="newsDate" class="form-control"  placeholder="请选择发布日期" value="{{ newsDate }}" onclick="SelectDate(this,'yyyy-MM-dd')" />
			</div>
            <input type=hidden name=currentPage value="{{ currentPage }}" />
            <button type="submit" class="btn btn-primary">查询</button>
        </form>
	</div>

	<div class="col-md-9 wow fadeInRight">
		<ul class="breadcrumb">
  			<li><a href="{% url 'Index:index' %}">首页</a></li>
  			<li><a href="{% url 'News:frontList' %}">新闻信息信息列表</a></li>
  			<li class="active">查询结果显示</li>
  			<a class="pull-right" href="{% url 'News:frontAdd' %}" style="display:none;">添加新闻信息</a>
		</ul>
		<div class="row">
            {% for news in newss_page %}
                {% if forloop.counter|add:-1|divisibleby:4 %}
			<div class="col-md-3 bottom15" style="clear: left;">
                {% else %}
            <div class="col-md-3 bottom15">
                {% endif %}
			  <a  href="{% url 'News:frontShow' news.newsId %}"><img class="img-responsive" src="{{ news.newsPhoto.url }}" /></a>
			     <div class="showFields">
			     	<div class="field">
	            		记录编号:{{ news.newsId }}
			     	</div>
			     	<div class="field">
	            		新闻标题:{{ news.newsTitle }}
			     	</div>
			     	<div class="field">
	            		新闻内容:{{ news.newsContent }}
			     	</div>
			     	<div class="field">
	            		发布日期:{{ news.newsDate }}
			     	</div>
			        <a class="btn btn-primary top5" href="{% url 'News:frontShow' news.newsId  %}">详情</a>
			        <a class="btn btn-primary top5" onclick="newsEdit('{{ news.newsId }}');" style="display: none;">修改</a>
			        <a class="btn btn-primary top5" onclick="newsDelete('{{ news.newsId }}');" style="display: none;">删除</a>
			     </div>
			</div>
			{% endfor %}

			<div class="row">
				<div class="col-md-12">
					<nav class="pull-left">
						<ul class="pagination">
							<li><a href="#" onclick="GoToPage({{ currentPage|add:-1 }},{{ totalPage }});" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
							{% for page in pageList %}
                                            {% if currentPage == page %}
						                        <li class="active"><a href="#"  onclick="GoToPage({{ page }},{{ totalPage }});">{{ page }}</a></li>
						                    {% else %}
                                                <li><a href="#"  onclick="GoToPage({{ page }},{{ totalPage }});">{{ page }}</a></li>
                                            {% endif %}
                                            {% endfor %}
						                    <li><a href="#" onclick="GoToPage({{ currentPage|add:1 }},{{ totalPage }});"><span aria-hidden="true">&raquo;</span></a></li>
						</ul>
					</nav>
					<div class="pull-right" style="line-height:75px;" >共有{{ recordNumber }}条记录，当前第{{ currentPage }}/{{ totalPage }} 页</div>
				</div>
			</div>
		</div>
	</div>

  </div>
</div>
<div id="newsEditDialog" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><i class="fa fa-edit"></i>&nbsp;新闻信息信息编辑</h4>
      </div>
      <div class="modal-body" style="height:450px; overflow: scroll;">
      	<form class="form-horizontal" name="newsEditForm" id="newsEditForm" enctype="multipart/form-data" method="post"  class="mar_t15">
		    {% csrf_token %}
		  <div class="form-group">
			 <label for="news_newsId_edit" class="col-md-3 text-right">记录编号:</label>
			 <div class="col-md-9"> 
			 	<input type="text" id="news_newsId_edit" name="news.newsId" class="form-control" placeholder="请输入记录编号" readOnly>
			 </div>
		  </div> 
		  <div class="form-group">
		  	 <label for="news_newsTitle_edit" class="col-md-3 text-right">新闻标题:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="news_newsTitle_edit" name="news.newsTitle" class="form-control" placeholder="请输入新闻标题">
			 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="news_newsContent_edit" class="col-md-3 text-right">新闻内容:</label>
		  	 <div class="col-md-9">
			    <textarea id="news_newsContent_edit" name="news.newsContent" rows="8" class="form-control" placeholder="请输入新闻内容"></textarea>
			 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="news_newsDate_edit" class="col-md-3 text-right">发布日期:</label>
		  	 <div class="col-md-9">
                <div class="input-group date news_newsDate_edit col-md-12" data-link-field="news_newsDate_edit" data-link-format="yyyy-mm-dd">
                    <input class="form-control" id="news_newsDate_edit" name="news.newsDate" size="16" type="text" value="" placeholder="请选择发布日期" readonly>
                    <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
                    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                </div>
		  	 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="news_newsPhoto_edit" class="col-md-3 text-right">新闻图片:</label>
		  	 <div class="col-md-9">
			    <img  class="img-responsive" id="news_newsPhotoImg" border="0px"/><br/>
			    <input id="news_newsPhoto" name="news.newsPhoto" type="file" size="50" />
		  	 </div>
		  </div>
		</form> 
	    <style>#newsEditForm .form-group {margin-bottom:5px;}  </style>
      </div>
      <div class="modal-footer"> 
      	<button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
      	<button type="button" class="btn btn-primary" onclick="ajaxNewsModify();">提交</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-datetimepicker.min.js' %}"></script>
<script src="{% static 'plugins/locales/bootstrap-datetimepicker.zh-CN.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jsdate.js' %}"></script>
<script>
/*跳转到查询结果的某页*/
function GoToPage(currentPage,totalPage) {
    if(currentPage==0) return;
    if(currentPage>totalPage) return;
    document.newsQueryForm.currentPage.value = currentPage;
    document.newsQueryForm.submit();
}

/*可以直接跳转到某页*/
function changepage(totalPage)
{
    var pageValue=document.newsQueryForm.pageValue.value;
    if(pageValue>totalPage) {
        alert('你输入的页码超出了总页数!');
        return ;
    }
    document.newsQueryForm.currentPage.value = pageValue;
    documentnewsQueryForm.submit();
}

/*弹出修改新闻信息界面并初始化数据*/
function newsEdit(newsId) {
	$.ajax({
		url :  '/News/update/' + newsId,
		type : "get",
		dataType: "json",
		success : function (news, response, status) {
			if (news) {
				$("#news_newsId_edit").val(news.newsId);
				$("#news_newsTitle_edit").val(news.newsTitle);
				$("#news_newsContent_edit").val(news.newsContent);
				$("#news_newsDate_edit").val(news.newsDate);
				$("#news_newsPhotoImg").attr("src", news.newsPhoto);
				$('#newsEditDialog').modal('show');
			} else {
				alert("获取信息失败！");
			}
		}
	});
}

/*删除新闻信息信息*/
function newsDelete(newsId) {
    var csrf = $('input[name="csrfmiddlewaretoken"]').val();
	if(confirm("确认删除这个记录")) {
		$.ajax({
			type : "POST",
			url : "/News/deletes",
			data : {
				newsIds : newsId,
                "csrfmiddlewaretoken": csrf
			},
			success : function (obj) {
				if (obj.success) {
					alert("删除成功");
					$("#newsQueryForm").submit();
					//location.href= basePath + "News/frontlist";
				}
				else 
					alert(obj.message);
			},
		});
	}
}

/*ajax方式提交新闻信息信息表单给服务器端修改*/
function ajaxNewsModify() {
	$.ajax({
		url :   '/News/update/' + $("#news_newsId_edit").val(),
		type : "post",
		dataType: "json",
		data: new FormData($("#newsEditForm")[0]),
		success : function (obj, response, status) {
            if(obj.success){
                alert("信息修改成功！");
                $("#newsQueryForm").submit();
            }else{
                alert(obj.message);
            } 
		},
		processData: false,
		contentType: false,
	});
}

$(function(){
	/*小屏幕导航点击关闭菜单*/
    $('.navbar-collapse a').click(function(){
        $('.navbar-collapse').collapse('hide');
    });
    new WOW().init();

    /*发布日期组件*/
    $('.news_newsDate_edit').datetimepicker({
    	language:  'zh-CN',  //语言
    	format: 'yyyy-mm-dd',
    	minView: 2,
    	weekStart: 1,
    	todayBtn:  1,
    	autoclose: 1,
    	minuteStep: 1,
    	todayHighlight: 1,
    	startView: 2,
    	forceParse: 0
    });
})
</script>
</body>
</html>


PythonProject/templates/News/news_frontshow.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
  <TITLE>查看新闻信息详情</TITLE>
  <link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
  <link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
  <link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
  <link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
</head>
<body style="margin-top:70px;"> 
{% include 'header.html' %}
<div class="container">
	<ul class="breadcrumb">
  		<li><a href={% url 'Index:index' %}">首页</a></li>
  		<li><a href="{% url 'News:frontList' %}">新闻信息信息</a></li>
  		<li class="active">详情查看</li>
	</ul>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">记录编号:</div>
		<div class="col-md-10 col-xs-6">{{ news.newsId }}</div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">新闻标题:</div>
		<div class="col-md-10 col-xs-6">{{ news.newsTitle }}</div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">新闻内容:</div>
		<div class="col-md-10 col-xs-6">{{ news.newsContent }}</div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">发布日期:</div>
		<div class="col-md-10 col-xs-6">{{ news.newsDate }}</div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">新闻图片:</div>
		<div class="col-md-10 col-xs-6"><img class="img-responsive" src="{{ news.newsPhoto.url }}"  border="0px"/></div>
	</div>
	<div class="row bottom15">
		<div class="col-md-2 col-xs-4"></div>
		<div class="col-md-6 col-xs-6">
			<button onclick="history.back();" class="btn btn-primary">返回</button>
		</div>
	</div>
</div> 
{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script>
$(function(){
        /*小屏幕导航点击关闭菜单*/
        $('.navbar-collapse a').click(function(){
            $('.navbar-collapse').collapse('hide');
        });
        new WOW().init();
 })
 </script> 
</body>
</html>
